// Generated by Farm.js. Do not edit.
declare module "*.avif" {
  const image: import("@farm.js/core/image").StaticImageData;
  export const src: string;
  export const width: number;
  export const height: number;
  export const blurDataURL: string | undefined;
  export default image;
}

declare module "*.gif" {
  const image: import("@farm.js/core/image").StaticImageData;
  export const src: string;
  export const width: number;
  export const height: number;
  export const blurDataURL: string | undefined;
  export default image;
}

declare module "*.jpeg" {
  const image: import("@farm.js/core/image").StaticImageData;
  export const src: string;
  export const width: number;
  export const height: number;
  export const blurDataURL: string | undefined;
  export default image;
}

declare module "*.jpg" {
  const image: import("@farm.js/core/image").StaticImageData;
  export const src: string;
  export const width: number;
  export const height: number;
  export const blurDataURL: string | undefined;
  export default image;
}

declare module "*.png" {
  const image: import("@farm.js/core/image").StaticImageData;
  export const src: string;
  export const width: number;
  export const height: number;
  export const blurDataURL: string | undefined;
  export default image;
}

declare module "*.webp" {
  const image: import("@farm.js/core/image").StaticImageData;
  export const src: string;
  export const width: number;
  export const height: number;
  export const blurDataURL: string | undefined;
  export default image;
}

declare module "*?url" {
  const src: string;
  export default src;
}
